### ISSUE TITLE
IE cache problems?

### ISSUE THREAD

**Issue by grossofans** [esheri3/OWASP-CSRFGuard#54]
how to solve IE cache, cause repeat sending requests.
and then the csrfGurd works not as expected.

**Comment by pavanravikanthkondamudi** [comment]
apply  no cache request headers or use no cache meta tage...

**Comment by aramrami** [comment]
The active CSRFGuard projet is under my name aramrami. All request must be posted via this projet.
The version hosted here is an old version.
