### ISSUE TITLE
CSRFGuard reloads css, js files even though they are excluded in configuration

### ISSUE THREAD

**Issue by marcfasel** [esheri3/OWASP-CSRFGuard#71]
We included CSRFGuard in our Struts 1 application and now we can see a noticeable "blip" when each screen is rendered: it first renders fine, then you briefly see the page without any CSS (white background and only text) and then it goes back to normal.
Looking at the network traffic the css and js files are reloaded once the CSRFGuard JavaScript adds the csrf token, which causes the blip. This is unacceptable for us. I marked css, js, etc files as unprotected in the csrfGuard properties but the token is still attached.

This seems to be a known issue: http://lists.owasp.org/pipermail/owasp-csrfguard/2013-October/000257.html

Is there something I can do about that?

**Comment by skepticfx** [comment]
I believe the latest version, injects the tokens only into `form` tags. https://github.com/esheri3/OWASP-CSRFGuard/blob/master/csrfguard/src/main/resources/csrfguard.js#L342

**Comment by marcfasel** [comment]
Just realised that this is not the official version 3.1.0 of CSRFGuard. Will post on https://github.com/aramrami/OWASP-CSRFGuard
